# File: install_easy_module.yml
# Description:
#   Standardized EASY module installation
# Parameters:
#   easy_module_name - name of the EASY module to configure
#   easy_module_version - version of the EASY module
# Globals:
#   See includes called from this script.

- name: Create a user for the module
  user: name={{ easy_module_name }}

- include: download_module_tar.yml

- include: unarchive_to_server.yml

- name: Create facts for module
  template: src=fact.py dest=/etc/ansible/facts.d/{{ easy_module_name|replace('-', '_') }}.fact mode="u+x"
