# File: install_easy_module.yml
# Description:
#   Standardized EASY module installation
# Parameters:
#   easy_module_name - name of the EASY module to configure
#   easy_module_version - version of the EASY module
# Globals:
#   See includes called from this script.

- include: download_module_tar.yml

- include: unarchive_to_server.yml
